name: Deploy to WordPress.org
on:
  push:
    branches:
    - trunk
jobs:
  trunk:
    name: Push to trunk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build js
      run: |
        npm install
        npm run build
    - uses: actions/checkout@master
    - name: WordPress.org plugin update
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        README_NAME: readme.md
        VERSION: '0.0.40'
        SLUG: 'presentation-block'
